project:
  type: website

website:
  title: "Stats for Scared Ecologists"
  navbar:
    left:
      - text: "Home"
        file: index.qmd
      - text: "Blog"
        file: blog.qmd
      - text: "About me"
        file: about.qmd
    right:
      - icon: github
        href: https://github.com/rlbarter
      - icon: twitter
        href: https://twitter.com/statsecology
      - icon: rss
        href: index.xml
  twitter-card: true
format:
  html:
    theme: simplex
    linkcolor: "#6633c4"
    code-copy: true
    footnotes-hover: true
    css: styles.css

editor: source

